---

name: Build Storybook
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run build-storybook
      env:
        CI: true
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: commit
      run: |
        git merge origin/main -m "Merge remote-tracking branch 'origin/main'"
        git add .
        git commit -m "chore: Storybook Update"
        git push origin main
