name: Tests and Linting

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run lint:css
    - run: npm run concurrently -k -s first -n \"SB,TEST\" -c \"magenta,blue\" \"npm run build-storybook --quiet && npx http-server storybook --port 6006 --silent\" \"wait-on tcp:6006 && npm run test-storybook\"
    #- run: npm run build-storybook
    #- run: npm run storybook
    #- run: npm run test-storybook
      env:
        CI: true
