---

name: Semantic Release
on:
  push:
    branches:
      - "main"

jobs:
  release:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      packages: write
      contents: write
      issues: read
    runs-on: [self-hosted, Linux, prod]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # Pulls all history and tags for lerna to detect what packages changed
          token: ${{ secrets.GH_PAT }} # This token is available by default
      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.13.0"
          registry-url: https://npm.pkg.github.com/
          scope: '@WESCO-International' 
      - run:  cat .npmrc
      - name: GIT PREPARE REPOSITORY
        run: git checkout ${{ github.event.release.target_commitish }} && git pull # Checkout and pull the release target branch
      - name: GIT USER CONFIG
        run: |
          git config user.name GitHub-Actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com # Config user name and email for lerna publish commit
      - run: npm install          
      - run: npm run build
      - run: npm run postcss:build
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: commit
        run: |
          git add .
          git commit -m "Design System Update"
          git push origin main
